name: Build

on: [push, workflow_dispatch]

jobs:
  run-tests:
    name: Build and Test
    runs-on: ubuntu-24.04
    steps:
      - id: version
        name: Get semantic version
        uses: spritely/actions.semantic-version/get@ad16b721c3e5d07b2a678a4f4c7dbad881667c36 # v0.7.31

      - name: Run tests
        uses: ./tests

      - name: Apply semantic version
        if: ${{ steps.version.outputs.branchName == github.event.repository.default_branch }}
        uses: spritely/actions.semantic-version/apply@ad16b721c3e5d07b2a678a4f4c7dbad881667c36 # v0.7.31
        with:
          version: ${{ steps.version.outputs.version }}
