name: Build

on: [push, workflow_dispatch]

jobs:
  run-tests:
    name: Build and Test
    runs-on: ubuntu-24.04
    steps:
      - id: version
        name: Get semantic version
        uses: spritely/actions.semantic-version/get@7fb99a6172210998c6b19b401d7304e83f7deca8 # v0.7.30

      - name: Run tests
        uses: ./tests

      - name: Apply semantic version
        if: ${{ steps.version.outputs.branchName == github.event.repository.default_branch }}
        uses: spritely/actions.semantic-version/apply@7fb99a6172210998c6b19b401d7304e83f7deca8 # v0.7.30
        with:
          version: ${{ steps.version.outputs.version }}
