name: Build

on: [push, workflow_dispatch]

jobs:
  run-tests:
    name: Build and Test
    runs-on: ubuntu-24.04
    steps:
      - id: version
        name: Get semantic version
        uses: spritely/actions.semantic-version/get@1b7d5488fa697ab2c88ca915fe253ba9050e68b9 # v0.7.18

      - name: Run tests
        uses: ./tests

      - name: Apply semantic version
        if: ${{ steps.version.outputs.branchName == github.event.repository.default_branch }}
        uses: spritely/actions.semantic-version/apply@1b7d5488fa697ab2c88ca915fe253ba9050e68b9 # v0.7.18
        with:
          version: ${{ steps.version.outputs.version }}
