name: Build

on: [push, workflow_dispatch]

jobs:
  run-tests:
    name: Build and Test
    runs-on: ubuntu-24.04
    steps:
      - id: version
        name: Get semantic version
        uses: spritely/actions.semantic-version/get@v0.2.0

      - id: setup-tests
        name: Start container registry
        run: |
          docker run -d -p 5000:5000 \
            -v ${{ github.workspace }}/tests/auth:/auth \
            -e REGISTRY_AUTH=htpasswd \
            -e REGISTRY_AUTH_HTPASSWD_REALM="Registry Realm" \
            -e REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd \
            --name registry registry:2

      - name: Run test - Publish container publishes expected container
        uses: ./tests/basic-test
        if: always() && steps.setup-tests.outcome == 'success'

      - name: Run test - Publish container uses provided summary template
        uses: ./tests/custom-template-test
        if: always() && steps.setup-tests.outcome == 'success'

      - name: Run test - Publish container publishes multiple images
        uses: ./tests/multiple-images-test
        if: always() && steps.setup-tests.outcome == 'success'

      - name: Run test - Publish container build secrets
        uses: ./tests/secrets-test
        if: always() && steps.setup-tests.outcome == 'success'

      - id: test-report
        name: Generate test report
        uses: dorny/test-reporter@v1.9.1
        if: always()
        with:
          name: Test Results
          path: test-results/*.xml
          reporter: java-junit

      - name: Add test report link
        if: always()
        run: |
          echo "## Test Report" >> $GITHUB_STEP_SUMMARY
          
          if [ "${{ steps.test-report.outcome }}" == "success" ]; then
            echo "  - Total: ${{ steps.test-report.outputs.total }} tests" >> $GITHUB_STEP_SUMMARY
            echo "  - Passed: ${{ steps.test-report.outputs.passed }}" >> $GITHUB_STEP_SUMMARY
            echo "  - Failed: ${{ steps.test-report.outputs.failed }}" >> $GITHUB_STEP_SUMMARY
          fi

          echo "- [View detailed test results](${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}?check_suite_focus=true#step:${GITHUB_JOB}:${GITHUB_RUN_ATTEMPT})" >> $GITHUB_STEP_SUMMARY
          

      - name: Apply semantic version
        if: ${{ steps.version.outputs.branchName == github.event.repository.default_branch }}
        uses: spritely/actions.semantic-version/apply@v0.2.0
        with:
          version: ${{ steps.version.outputs.version }}
