name: Run Publish Container Tests

on: [push, workflow_dispatch]

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Start container registry
        run: |
          docker run -d -p 5000:5000 \
            -v ${{ github.workspace }}/tests/auth:/auth \
            -e REGISTRY_AUTH=htpasswd \
            -e REGISTRY_AUTH_HTPASSWD_REALM="Registry Realm" \
            -e REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd \
            --name registry registry:2

      - name: Run test - Publish container publishes expected container
        uses: ./tests/basic-test

      - name: Run test - Publish container uses provided summary template
        uses: ./tests/custom-template-test

      - name: Run test - Publish container publishes multiple images
        uses: ./tests/multiple-images-test

      - name: Run test - Publish container build secrets
        uses: ./tests/secrets-test
