name: Run Publish Container Tests

on: [push, workflow_dispatch]

jobs:
  setup-container-registry:
    name: Setup container registry
    runs-on: ubuntu-24.04
    steps:
      - name: Setup container registry
        run: |
          mkdir -p auth
          htpasswd -Bbn testuser testpassword > auth/htpasswd

          docker run -d -p 5000:5000 \
            -v auth:/auth \
            -e REGISTRY_AUTH=htpasswd \
            -e REGISTRY_AUTH_HTPASSWD_REALM="Registry Realm" \
            -e REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd \
            --name registry registry:2

      - name: Validate container registry is running
        run: |
          curl -u testuser:testpassword http://localhost:5000/v2/ || exit 1
          echo "\nRegistry is running"

  basic-test:
    name: Basic test
    needs: setup-container-registry
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run basic test
        uses: ./tests/basic-test