name: Run Publish Container Tests

on: [push, workflow_dispatch]

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-24.04
    steps:
      - id: version
        name: Get semantic version
        uses: spritely/actions.semantic-version/get@v0.2.0

      - id: setup-tests
        name: Start container registry
        run: |
          docker run -d -p 5000:5000 \
            -v ${{ github.workspace }}/tests/auth:/auth \
            -e REGISTRY_AUTH=htpasswd \
            -e REGISTRY_AUTH_HTPASSWD_REALM="Registry Realm" \
            -e REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd \
            --name registry registry:2

      - name: Run test - Publish container publishes expected container
        uses: ./tests/basic-test
        if: always() && steps.setup-tests.outcome == 'success'

      - name: Run test - Publish container uses provided summary template
        uses: ./tests/custom-template-test
        if: always() && steps.setup-tests.outcome == 'success'

      - name: Run test - Publish container publishes multiple images
        uses: ./tests/multiple-images-test
        if: always() && steps.setup-tests.outcome == 'success'

      - name: Run test - Publish container build secrets
        uses: ./tests/secrets-test
        if: always() && steps.setup-tests.outcome == 'success'

      - name: Generate test report
        uses: dorny/test-reporter@v1.9.1
        if: always()
        with:
          name: Test Results
          path: test-results/*.xml
          reporter: java-junit

      - name: Apply semantic version
        if: ${{ steps.version.outputs.branchName == github.event.repository.default_branch }}
        uses: spritely/actions.semantic-version/apply@v0.2.0
        with:
          version: ${{ steps.version.outputs.version }}
